language: node_js
node_js: '10'

os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
    - fakeroot
    - rpm

script:
- npm run lint
- npm run publish