name: Build and Release
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn install

      - name: Build and Publish Electron app
        run: yarn run publish

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: out

  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          draft: ${{ github.event_name == 'pull_request' }}
          prerelease: false
          files: |
            ${{steps.download.outputs.download-path}}/**/*.deb
            ${{steps.download.outputs.download-path}}/**/*.rpm
            ${{steps.download.outputs.download-path}}/**/*.nupkg
            ${{steps.download.outputs.download-path}}/**/*.exe
